context("alignranks")
source("alignranks.R")

test_that("test for correct format",{
  set.seed(101)
  dat<-matrix(runif(20),10,2)
  dat[,1]<-sort(dat[,1])
  dat[,2]<-sort(dat[,2])
  sims<-array(runif(60),c(10,2,3))
  res<-alignranks(dat,sims)
  expect_equal(dim(sims),dim(res))
})

test_that("test for quantitative accuracy",{
  set.seed(101)
  dat<-matrix(runif(20),10,2)
  dat[,1]<-sort(dat[,1])
  dat[,2]<-sort(dat[,2])
  sims<-array(runif(60),c(10,2,3))
  res<-alignranks(dat,sims)
  expect_equal(sort(res[,1,1]),sort(dat[,1]))
  expect_equal(sort(res[,2,1]),sort(dat[,2]))
  expect_equal(sort(res[,1,2]),sort(dat[,1]))
  expect_equal(sort(res[,2,2]),sort(dat[,2]))
  expect_equal(rank(sims[,1,1]),rank(res[,1,1]))  
  expect_equal(rank(sims[,2,1]),rank(res[,2,1]))  
  expect_equal(rank(sims[,1,2]),rank(res[,1,2]))  
  expect_equal(rank(sims[,2,2]),rank(res[,2,2]))  
})
